act_spec: false
batchsize: 32
classification_model: true
dataset_path: ./VO_data
depth_d_planes: 10
device: cuda:1
dof: 3
eval_iter: 1000
hfov: 70
log_name: vo_irgbd_ttexture_3frame_cmodel_20epoch
log_path: ./train_log
loop_loss: false
loop_loss_coef: 0.01
loop_loss_max_inc: 3
lr: 0.0001
max_depth: 10
min_depth: 0.1
num_frame: 3
pose_height: 256
pose_inputs: rgbd
pose_width: 256
print_iter: 10
rec_loss_coef: 2.0
rec_target: texture
reuse: false
reuse_iter: -1
reuse_name: null
rgb_height: 256
rgb_width: 256
rot_coef: 0.01
run_type: train_no_noise
save_iter: 5000
train_epoch: 20
train_scale: 1
trans_coef: 0.01
